const List<String> wordPool = [
  "perro",
  "gato",
  "coche",
  "coche rojo",
  "coche blanco",
  "bicicleta",
  "patinete",
  "autobús",
  "semáforo",
  "señal de stop",
  "farola",
  "banco",
  "papelera",
  "grafiti",
  "tienda",
  "edificio alto",
  "ventana",
  "puerta",
  "persona con gorra",
  "persona con mochila",
  "árbol",
  "flor",
  "moto",
  "taxi",
  "camión",
  "perro pequeño",
  "perro grande",
  "gato negro",
  "gato blanco",
  "coche azul",
  "coche negro",
  "coche antiguo",
  "bicicleta roja",
  "bicicleta azul",
  "parque",
  "columpio",
  "fuente",
  "terraza",
  "café",
  "restaurante",
  "pizza",
  "hamburguesa",
  "helado",
  "persona corriendo",
  "persona hablando por teléfono",
  "persona con gafas",
  "niño",
  "anciano",
  "pareja",
  "grupo de amigos",
  "perro con correa",
  "gato en ventana",
  "pájaro",
  "paloma",
  "cielo",
  "nube",
  "atardecer",
  "sombra",
  "reflejo",
  "espejo",
  "cristal",
  "balcón",
  "escalera",
  "ascensor",
  "puerta abierta",
  "puerta cerrada",
  "reja",
  "graffiti grande",
  "grafiti pequeño",
  "cartel",
  "anuncio",
  "logo",
  "marca",
  "zapatos",
  "mochila",
  "bolso",
  "reloj",
  "gafas de sol",
  "sombrero",
  "gorra",
  "bufanda",
  "guantes",
  "bebida",
  "botella",
  "lata",
  "vaso",
  "taza",
  "ordenador",
  "portátil",
  "tablet",
  "móvil",
  "pantalla",
  "televisión",
  "luz",
  "vela",
  "linterna",
];