// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIyy7uLyFsQ2y0T-XV-ybsYxQfb9_9x1c',
    appId: '1:149916352842:web:c8f68adba77e6dafc4c1b3',
    messagingSenderId: '149916352842',
    projectId: 'hiddo-1f412',
    authDomain: 'hiddo-1f412.firebaseapp.com',
    storageBucket: 'hiddo-1f412.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA453UtsmGdSw0H5YonTTwkzts_9Dvv8co',
    appId: '1:149916352842:android:2b3cb518fcc49d3dc4c1b3',
    messagingSenderId: '149916352842',
    projectId: 'hiddo-1f412',
    storageBucket: 'hiddo-1f412.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7DMmiRflO0ra8QLOXTPMaVejrJy76tYc',
    appId: '1:149916352842:ios:09ade3bcd8d50aa3c4c1b3',
    messagingSenderId: '149916352842',
    projectId: 'hiddo-1f412',
    storageBucket: 'hiddo-1f412.firebasestorage.app',
    iosBundleId: 'com.example.hiddo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7DMmiRflO0ra8QLOXTPMaVejrJy76tYc',
    appId: '1:149916352842:ios:09ade3bcd8d50aa3c4c1b3',
    messagingSenderId: '149916352842',
    projectId: 'hiddo-1f412',
    storageBucket: 'hiddo-1f412.firebasestorage.app',
    iosBundleId: 'com.example.hiddo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIyy7uLyFsQ2y0T-XV-ybsYxQfb9_9x1c',
    appId: '1:149916352842:web:d9fe2147fadac990c4c1b3',
    messagingSenderId: '149916352842',
    projectId: 'hiddo-1f412',
    authDomain: 'hiddo-1f412.firebaseapp.com',
    storageBucket: 'hiddo-1f412.firebasestorage.app',
  );
  
}
